name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf automake libtool
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Create Google Key File
      run: |
        echo "${{ secrets.GOOGLE_KEY_JSON }}" > replacement-463907-07ae6e152f37.json

    - name: Build with Buildozer
      run: |
        yes | buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: WMS-App-APK
        path: bin/*.apk
